SLURM_JOBID:  18262944
SLURM_ARRAY_TASK_ID:  15
SLURM_ARRAY_JOB_ID:  18262928
2021-03-19 15:50:46.934503: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arcts/centos7/python3.6-anaconda/5.2.0/lib:/opt/slurm/lib64::
2021-03-19 15:50:46.934539: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "summary2.py", line 153, in <module>
    seed_data = seeds[i, 0]
IndexError: index 15 is out of bounds for axis 0 with size 10
